"""
<<<<<<< HEAD
Django settings for crowdFunding08 project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
=======
Django settings for crowdFunding project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
>>>>>>> d36c4b517eab3c21da3097626b93ef170b2a126d
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kpxv#r25$y2ls^ivcm&xl(#1t(@=9m3dp1+6vh6@nd#u(sv6=%'
=======
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't-qcu#dj9@cqi^z_0fc5w&-345jvp9!+m_ebikbvg#ie43*7vj'
>>>>>>> d36c4b517eab3c21da3097626b93ef170b2a126d

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin','project',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<< HEAD
ROOT_URLCONF = 'crowdFunding08.urls'
=======
ROOT_URLCONF = 'crowdFunding.urls'
>>>>>>> d36c4b517eab3c21da3097626b93ef170b2a126d

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<< HEAD
WSGI_APPLICATION = 'crowdFunding08.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
=======
WSGI_APPLICATION = 'crowdFunding.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
>>>>>>> d36c4b517eab3c21da3097626b93ef170b2a126d

DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.mysql',
        'NAME': 'crowdFunding6',
        'USER': 'root',
        'HOST': 'localhost',

    }
}

<<<<<<< HEAD

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
=======
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators
>>>>>>> d36c4b517eab3c21da3097626b93ef170b2a126d

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.0/topics/i18n/
=======
# https://docs.djangoproject.com/en/2.1/topics/i18n/
>>>>>>> d36c4b517eab3c21da3097626b93ef170b2a126d

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.0/howto/static-files/
=======
# https://docs.djangoproject.com/en/2.1/howto/static-files/
>>>>>>> d36c4b517eab3c21da3097626b93ef170b2a126d

STATIC_URL = '/static/'
